language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.1

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf

install:
  # Pillar installation
  - git clone https://github.com/pillar-markup/pillar.git -b dev-7 # Clone pillar
  - cd pillar && ./scripts/build.sh && cd ..                              # Run pillar build script. Pillar will be built in `pwd`/build!
  - . pillar/scripts/ci/ensure_latex.sh                                   # Install latex
  - ./pillar/scripts/ci/ensure_book_dependencies.sh                       # Install latex dependencies required by pillar
  
script:
  - ./pillar/build/pillar build pdf
deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-Reflectivity
  skip_cleanup: true
  user: ducasse
  key:
    secure: PJk8lIZXeUnjAwQLIxO3WfBf1DMnbHj1QX5rsKvFUGrKAP5fMqtd+zC7bxvYSdzaEEHZG8foPQnNmhiELvhym9+8xsSHSWR9n8MMAKUieHxPM093InRW5JpnEMtTTRRH5zsbG8VPqge0mGMqKt5pBgt+gvu88v2Q+VR7ZWkeIWxhKZwXoksoQPwDeQAmhhgnBXYVxjCb61jgx6wWUsWGsgoiIgyeedB/0V7nEV0Nvi6KJq5xAyxR3Xvk/fXFI40xERurbLt1WUZPbx/v/BoLoS+z+SNHHQ6rycHxU4tfi4izxYTwz0h6lzUbGIOpgk47eKT5if3V1LPUUrYMmWZ+nbQ2aIzm8ZaTNjmjolmpga4ATdd35vA4VahpZqaEWbbJ6mQ8FFCCc95CK+T2rDbul5Q4u7nQWHFAEjcFY1I3Nim0bcaR0umCAzD24GvHTw/CW8TjoyktKULJOFvIvJlJ3q
- provider: releases
  file: build/reflectivity.spiral.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
